collections:
#  - name: redhat.insights
  - name: chocolatey.chocolatey
  - name: community.windows
  - name: community.general
  - name: ansible.windows
  - name: ansible.posix
  - name: splunk.es
  - name: shadowman.reports
    source: https://github.com/shadowman-lab/shadowman.reports.git
    type: git
    version: main
  - name: community.postgresql
