---
- name: Create Linux Report
  hosts: all

  collections:
    - shadowman.reports

  tasks:

    - name: Scan Systems for detailed report
      ansible.builtin.include_role:
        name: shadowman_scan_systems
      when: detailedreport == 'True'

    - name: Debug collections
      command: ansible-galaxy collection list
      register: collections_out

    - debug:
        var: collections_out.stdout_lines

    - name: Show collections path
     debug:
       msg: "{{ lookup('env','ANSIBLE_COLLECTIONS_PATHS') }}"   
   

    - name: Build the report
      ansible.builtin.include_role:
        name: build_report_linux
        apply:
          delegate_to: "{{ groups['report_server'][0] }}"
          run_once: true
